places = ['Maldivas', 'Dubai', 'New York', 'Fernando de Noronha', 'Arraial do Cabo']
print(places)
print(f'Em ordem alfabética: {sorted(places)}')
print(places)
print(f'Em ordem alfabética reversa: {sorted(places, reverse=True)}')
print(places)
places.reverse()
print(places)
places.reverse()
print(places)
places.sort()
print(places)
places.sort(reverse=True)
print(places)